# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd9b9893e7e97f94ebe3801ce350944ca22c2201ce93e0ac5cf2ef6e569e2bbe0b8b09c334335c601d8622b21beec1e5f4261310350cba6fe7dacc15abd3c606

test:
  secret_key_base: 521ca073bc4a7b9b8b3f79b3e7e6f46e0d8638d03dd23b8bbeb6470fb1ef3e8fe30b1b20df98363d519ae692e636a23ebc197fce7c714f0a023180162fb298cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
